# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question_text', models.TextField(max_length=200)),
            ],
        ),
    ]
